name: deployfe

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  dockerbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: unravelmalang/unravel-fe:latest

  pulljobs:
      runs-on: ubuntu-latest
      needs: dockerbuild
      steps:
      - name: compose up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
           cd ~/geo/appfe
           echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker compose pull
           echo ${{ secrets.SSH_PASSWORD }} | sudo docker compose up -d
           
            
      
    

